version: "3.4"
services:
  db:
    image: yzh44yzh/wg_forge_backend_env:1.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 3m30s
    restart: always
    ports:
      - "5432:5432"
  web-server:
    image: web
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - "8080:8080"
    restart: always