version: "3.4"
services:
  db:
    image: postgr
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
  web-server:
    image: web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    #restart: always