version: "3.4"
services:
  db:
    image: yzh44yzh/wg_forge_backend_env:1.1
    restart: always
    ports:
      - "5432:5432"
  web-server:
    image: web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always